version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Nodejs Version
          command: node --version
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Packages
          command: yarn install --frozen-lockfile
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Test and Coverage
          command: |
            yarn test --coverage
