version: 2.1
executors:
  defaults:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    working_directory: ~/continuous-integration

jobs:
  build:
    executor: defaults
    steps:
      - checkout
      - run:
          name: Nodejs Version
          command: node --version
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Packages
          command: yarn install --frozen-lockfile
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Test and Coverage
          command: |
            yarn test --coverage
      - run:
          name: Coverage
          when: on_success
          command: |
            bash <(curl -s https://codecov.io/bash) -Z -C $CIRCLE_SHA1
      - run:
          name: Build
          when: on_success
          command: |
            yarn build
  deploy:
    executor: defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "51:82:9f:88:37:12:a6:4a:09:b0:5d:a7:d5:3e:99:f5"
      - run:
          name: 'Add known_hosts'
          command: |
            ssh -vvv ${USER_SSH}@${REMOTE_IP_SERVER}
      - run:
          name: 'Add known_hosts'
          command: |
            #ssh-keyscan ${REMOTE_IP_SERVER} >> ~/.ssh/known_hosts
            #echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
            #ssh-keyscan ${REMOTE_IP_SERVER}
            #ssh -o "StrictHostKeyChecking=no" ${USER_SSH}@${REMOTE_IP_SERVER}
            echo '***********************************************';
            #cat ~/.ssh/known_hosts
      - run:
          name: 'Install rsync'
          command: |
            sudo apt-get update && sudo apt-get install rsync
      - run:
          name: 'Copying project to server'
          command: |
            ls -l ~
            ls -l ~/continuous-integration
            rsync -e "ssh -o StrictHostKeyChecking=no" -avc --exclude='.git' --exclude='.circleci' --delete ~/continuous-integration/public ${USER_SSH}@${REMOTE_IP_SERVER}:${REMOTE_PATH}

workflows:
  version: 2.1
  notify_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master