version: 2.1
executors:
  defaults:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    working_directory: ~/continuous-integration

jobs:
  build:
    executor: defaults
    steps:
      - checkout
      - run:
          name: Nodejs Version
          command: node --version
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Packages
          command: yarn install --frozen-lockfile
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Test and Coverage
          command: |
            yarn test --coverage
      - run:
          name: Coverage
          when: on_success
          command: |
            bash <(curl -s https://codecov.io/bash) -Z -C $CIRCLE_SHA1
      - run:
          name: Build
          when: on_success
          command: |
            yarn build
  deploy:
    executor: defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ee:83:9b:5d:b1:2c:5c:29:76:b0:19:0c:2c:93:95:ea"
      - run:
          name: 'Install rsync'
          command: |
            sudo apt-get update && sudo apt-get install rsync
      - run:
          name: 'Copying project to server'
          command: |
            ls -l ~
            ls -l ~/continuous-integration
            sudo rsync -e "ssh -o StrictHostKeyChecking=no" -va --exclude .git --delete ~ ${USER_SSH}@${REMOTE_IP_SERVER}:${REMOTE_PATH}

workflows:
  version: 2.1
  notify_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master